name: foshmed
description: A digital diary app with mood tracking and photo uploads.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.2

  # HTTP Requests
  http: ^1.2.1

  # Local Storage
  shared_preferences: ^2.2.3

  table_calendar: ^3.1.1         # Versi terbaru

  flutter_local_notifications: ^16.3.2

  timezone: ^0.9.2

  # Image Handling
  image_picker: ^1.0.7           # Versi terbaru

  # PDF Generation
  pdf: ^3.10.8
  path_provider: ^2.1.2          # Versi terbaru

  # Date Formatting
  intl: ^0.19.0

  # Sharing
  share_plus: ^7.2.2

  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
          weight: 700